# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: vue-app:build # will run `yarn vue-app:build` command

    – uses: canastro/copy-file-action@master
      with:
        source: "packages/vue-app/CNAME"
        target: "packages/vue-app/dist/CNAME"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./packages/vue-app/dist
